### ISSUE TITLE
John Feedback

### ISSUE THREAD

**Issue by mohammadrezza** [wolf1128/polito-se2-24-03#16]
**Feedback for Workshop 5:**
**As John, the post office manager,**
The UI/UX was very well designed and implemented and it had enough details.
However, features like estimated time that were not working properly were unnecessary. If they don't work, keeping them on the page is useless.

**Comment by wolf1128** [comment]
Dear John,

Thanks for the feeback.
Your comments are so valuable to us. I'll make sure this message will be delivered to our dev team.

Regards,
Team#3.
