### ISSUE TITLE
Confusion about Assigned Counter Display for Tickets

### ISSUE THREAD

**Issue by AliceSantoro** [wolf1128/polito-se2-24-03#17]
I'm  Maria, a student customer.

Overall, I think the system is very user-friendly, but I’m facing some confusion about how the assigned counter for tickets is displayed after a ticket is retrieved.

Positive Feedback: I  mention a few things I really appreciated about the user interface:
Color Contrast: The contrast between different elements made the screen easy to read and navigate, which is great for usability.
User Navigation: Even though the full navigation wasn't completely implemented, the application felt intuitive, with buttons like "Go Home" and "Get Info" placed in convenient locations.

Issue: When I request a ticket (via the Get Ticket functionality), everything works as expected, and I receive the ticket. However, I’m unclear about how the system shows the assigned counter when it’s time to be served.

Specifically, I encountered a ticket where the assigned counter appeared, but I wasn't sure whether this was being displayed on a general board showing all tickets with their assigned counters, or if it was part of a personal screen intended just for my ticket.

Thank you for your time and assistance.

Best regards,
Maria

**Comment by vvo1f** [comment]
Dear Maria,

We appreciate your time and feedback. It means a lot for us.
By the way the structure of your text means you're more than an engineer than a student!

Thanks for the positive feedback.
Regarding the confusion, the point is when the customer tries to get the ticket based on the service then they can see the ticket details in the next page without specifying the counter. Later, in another page e.g. display board when he/she awaits to know their turn can see the counter, but, until then the counter still is unknown until the officer decides to call the next customer.
I hoper that I clarified the problem. Please let me know If it is not clear though.

Best Regards.
